const STORAGE={cart:"planetaFicha.cart.preview.v1",orders:"planetaFicha.orders.preview.v1",events:"planetaFicha.events.preview.v1",tickets:"planetaFicha.tickets.preview.v1"};
const state={filters:{category:"all",players:"all",difficulty:"all",search:""},cart:[],orders:[],events:readStorage(STORAGE.events,[]),tickets:[]};
const refs={grid:document.querySelector("#product-grid"),count:document.querySelector("#product-count"),empty:document.querySelector("#empty-state"),cartCount:document.querySelector("#cart-count"),floatingCartButton:document.querySelector("#floating-cart-button"),floatingCartCount:document.querySelector("#floating-cart-count"),cartDrawer:document.querySelector("#cart-drawer"),cartItems:document.querySelector("#cart-items"),cartSummary:document.querySelector("#cart-summary"),overlay:document.querySelector(".overlay"),productDialog:document.querySelector("#product-dialog"),checkoutDialog:document.querySelector("#checkout-dialog"),successDialog:document.querySelector("#success-dialog"),adminDialog:document.querySelector("#admin-dialog"),eventPreview:document.querySelector("#event-preview-content"),eventCount:document.querySelector("#event-count"),toast:document.querySelector("#toast")};
function showToast(message){refs.toast.textContent=message;refs.toast.classList.add("is-visible");clearTimeout(showToast.timeout);showToast.timeout=setTimeout(()=>refs.toast.classList.remove("is-visible"),2600);}
function openProduct(productId,index=0){const parent=products.find(p=>String(p.id)===String(productId));if(!parent)return;const versions=getVariants(parent);const total=versions.length;index=(index+total)%total;const product=versions[index];logEvent("product.viewed",{productId:String(product.id),productName:product.title});const variantNav=total>1?`<div class="variant-nav"><button class="variant-arrow" type="button" data-action="show-variant" data-id="${parent.id}" data-index="${index-1}" aria-label="Variante anterior">‹</button><div class="variant-dots">${versions.map((_,i)=>`<button class="variant-dot${i===index?" is-active":""}" type="button" data-action="show-variant" data-id="${parent.id}" data-index="${i}" aria-label="Ver variante ${i+1} de ${total}"${i===index?' aria-current="true"':''}></button>`).join("")}</div><button class="variant-arrow" type="button" data-action="show-variant" data-id="${parent.id}" data-index="${index+1}" aria-label="Variante siguiente">›</button></div>`:"";refs.productDialog.innerHTML=`<div><div class="dialog-product-image${product.image?" has-image":""}" style="--tone:${product.tone};--image-text:${product.text}">${product.image?`<img src="${safeText(product.image)}" alt="Caja del juego ${safeText(product.title)}" onerror="this.parentElement.classList.remove('has-image');this.remove()">`:""}<span>Diseño · ${safeText(product.origin)}</span>${variantNav}<strong>${safeText(product.title)}</strong></div><div class="dialog-product-content"><div class="dialog-header"><div><p class="eyebrow">${safeText(product.category)} · ${safeText(product.difficulty)}</p><h2 id="product-dialog-title">${safeText(product.title)}</h2></div><button class="icon-button" type="button" data-action="close-product" aria-label="Cerrar ficha">×</button></div><p class="detail-lead">${safeText(product.description)}</p><dl class="detail-meta"><div><dt>Jugadores</dt><dd>${safeText(product.players)}</dd></div><div><dt>Duración</dt><dd>${safeText(product.duration)}</dd></div><div><dt>Autoría</dt><dd>${safeText(product.author)}</dd></div><div><dt>Idioma</dt><dd>${safeText(product.language)}</dd></div><div><dt>Mecánicas</dt><dd>${safeText(product.mechanics)}</dd></div><div><dt>Disponibilidad</dt><dd>${product.stock>0?`En stock (${product.stock})`:"Agotado"}</dd></div></dl><div class="dialog-product-price"><b>${formatPrice(product.price)}</b><button class="button button-primary" type="button" data-action="add-cart" data-id="${product.id}"${product.stock<=0?' disabled':''}>Añadir al carrito <span>+</span></button></div></div></div>`;if(!refs.productDialog.open)refs.productDialog.showModal();}
function closeDialog(d){if(d?.open)d.close();}
document.addEventListener("click",e=>{const target=e.target.closest("[data-action],[data-admin-tab]");if(!target)return;const {action,id,change,adminTab,index}=target.dataset;if(adminTab){selectAdminTab(adminTab);return;}if(action==="toggle-mobile-menu"){const menu=document.querySelector("#mobile-menu");const open=menu.classList.toggle("is-open");target.setAttribute("aria-expanded",String(open));}else if(action==="open-cart")openCart();else if(action==="close-cart"||action==="close-overlays")closeCart();else if(action==="add-cart"){const added=addToCart(id);if(added&&refs.productDialog.open)closeDialog(refs.productDialog);}else if(action==="change-quantity")changeQuantity(id,change);else if(action==="view-product")openProduct(id);else if(action==="show-variant")openProduct(id,Number(index));else if(action==="close-product")closeDialog(refs.productDialog);else if(action==="start-checkout")openCheckout();else if(action==="close-checkout")closeDialog(refs.checkoutDialog);else if(action==="finish-order"){closeDialog(refs.successDialog);if(typeof renderAccountOrders==="function")renderAccountOrders();window.location.hash="catalogo";}else if(action==="open-admin")openAdmin();else if(action==="close-admin")closeDialog(refs.adminDialog);else if(action==="open-auth")openAuth();else if(action==="close-auth")closeAuth();else if(action==="show-register")showRegister();else if(action==="show-login")showLogin();else if(action==="logout")logoutUser();else if(action==="open-admin-from-account"&&isAdmin()){closeAuth();openAdmin();}else if(action==="toggle-filters"){const filters=document.querySelector("#filters");const visible=filters.classList.toggle("is-visible");target.setAttribute("aria-expanded",String(visible));}else if(action==="clear-filters"){state.filters={category:"all",players:"all",difficulty:"all",search:""};document.querySelector("#search-input").value="";document.querySelectorAll(".filter-pills").forEach(g=>g.querySelectorAll(".pill").forEach((b,i)=>b.classList.toggle("is-active",i===0)));renderCatalog();}else if(action==="export-events")exportEvents();else if(action==="clear-events")clearEvents();});
document.querySelectorAll("#mobile-menu a").forEach(a=>a.addEventListener("click",()=>{document.querySelector("#mobile-menu").classList.remove("is-open");document.querySelector(".mobile-menu-toggle").setAttribute("aria-expanded","false");}));
document.querySelector("#search-input").addEventListener("input",e=>{state.filters.search=e.target.value;renderCatalog();});
document.querySelectorAll(".filter-pills").forEach(group=>group.addEventListener("click",e=>{const b=e.target.closest(".pill");if(!b)return;group.querySelectorAll(".pill").forEach(p=>p.classList.toggle("is-active",p===b));state.filters[group.dataset.filterGroup]=b.dataset.value;renderCatalog();}));
document.querySelector("#checkout-form").addEventListener("submit",e=>{e.preventDefault();createOrder(e.currentTarget);});
document.querySelector("#checkout-form [name=promo]").addEventListener("input",updateCheckoutTotals);
document.querySelector("#support-form").addEventListener("submit",e=>{e.preventDefault();supportRequested(e.currentTarget);});
[refs.productDialog,refs.checkoutDialog,refs.successDialog,refs.adminDialog].forEach(d=>d?.addEventListener("click",e=>{if(e.target===d)d.close();}));
renderCatalog();syncCartForCurrentUser();renderEventPreview();initFloatingCart();updateRoleUI();
