<?php
declare(strict_types=1);
function pfMailSend(array $cfg,string $subject,string $body,string $replyTo=''): bool {
    if(empty($cfg['enabled'])) return false;
    if(empty($cfg['host'])||empty($cfg['username'])||empty($cfg['password'])||empty($cfg['from_email'])||empty($cfg['to_email'])) return false;
    $host=(string)$cfg['host'];$port=(int)($cfg['port']??587);$timeout=max(5,min((int)($cfg['timeout']??15),30));$implicit=$port===465;
    $ctx=stream_context_create(['ssl'=>['verify_peer'=>true,'verify_peer_name'=>true,'peer_name'=>$host,'SNI_enabled'=>true]]);
    $socket=@stream_socket_client(($implicit?'tls://':'tcp://').$host.':'.$port,$eno,$emsg,$timeout,STREAM_CLIENT_CONNECT,$ctx); if($socket===false)return false;
    $read=function()use($socket){$lines=[];do{$line=fgets($socket,515);if($line===false)throw new RuntimeException('SMTP cerrado');$lines[]=rtrim($line,"\r\n");}while(isset($line[3])&&$line[3]==='-');if(!preg_match('/^(\d{3})/',$lines[0],$m))throw new RuntimeException('SMTP inválido');return[(int)$m[1],implode("\n",$lines)];};
    $write=function(string $s)use($socket){while($s!==''){ $w=fwrite($socket,$s);if($w===false||$w===0)throw new RuntimeException('SMTP escritura');$s=substr($s,$w);}};
    $cmd=function(string $c,array $expected,string $step)use($write,$read){$write($c."\r\n");[$code,$resp]=$read();if(!in_array($code,$expected,true))throw new RuntimeException($step.' SMTP '.$code);return $resp;};
    try{stream_set_timeout($socket,$timeout);[$code]=$read();if($code!==220)throw new RuntimeException('SMTP greeting');$ehlo=$cmd('EHLO '.((string)parse_url((string)($cfg['ehlo']??'planetaficha.local'),PHP_URL_HOST)?:'planetaficha.local'),[250],'EHLO');if(!$implicit){if(stripos($ehlo,'STARTTLS')===false)throw new RuntimeException('SMTP sin STARTTLS');$cmd('STARTTLS',[220],'STARTTLS');if(@stream_socket_enable_crypto($socket,true,STREAM_CRYPTO_METHOD_TLS_CLIENT)!==true)throw new RuntimeException('TLS');$cmd('EHLO planetaficha.local',[250],'EHLO');}$cmd('AUTH LOGIN',[334],'AUTH');$cmd(base64_encode((string)$cfg['username']),[334],'usuario');$cmd(base64_encode((string)$cfg['password']),[235],'clave');$from=(string)$cfg['from_email'];$to=(string)$cfg['to_email'];$cmd('MAIL FROM:<'.$from.'>',[250],'MAIL');$cmd('RCPT TO:<'.$to.'>',[250,251],'RCPT');$cmd('DATA',[354],'DATA');$sub='=?UTF-8?B?'.base64_encode($subject).'?=';$headers=['Date: '.date(DATE_RFC2822),'From: '.($cfg['from_name']??'PlanetaFicha').' <'.$from.'>','To: <'.$to.'>','Subject: '.$sub,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64'];if($replyTo!=='')$headers[]='Reply-To: <'.$replyTo.'>';$message=implode("\r\n",$headers)."\r\n\r\n".rtrim(chunk_split(base64_encode($body),76,"\r\n"),"\r\n");$write($message."\r\n.\r\n");[$code]=$read();if($code!==250)throw new RuntimeException('SMTP DATA');$write("QUIT\r\n");return true;}catch(Throwable $e){error_log('[PlanetaFicha mail] '.$e->getMessage());return false;}finally{fclose($socket);}
}
