let authUser = null;
const authRefs={dialog:document.querySelector("#auth-dialog"),title:document.querySelector("#auth-title"),eyebrow:document.querySelector("#auth-eyebrow"),gateMessage:document.querySelector("#auth-gate-message"),loginLead:document.querySelector("#auth-login-lead"),loginView:document.querySelector("#auth-login-view"),registerView:document.querySelector("#auth-register-view"),accountView:document.querySelector("#auth-account-view"),loginForm:document.querySelector("#login-form"),registerForm:document.querySelector("#register-form"),loginError:document.querySelector("#login-error"),registerError:document.querySelector("#register-error"),accountButtonLabel:document.querySelector("#account-button-label"),accountName:document.querySelector("#account-name"),accountEmail:document.querySelector("#account-email"),accountRole:document.querySelector("#account-role"),accountOrders:document.querySelector("#account-orders"),accountAdminButton:document.querySelector("#account-admin-button"),adminAccess:document.querySelector("#admin-access")};
function currentUser(){return authUser;}
function isAuthenticated(){return !!authUser;}
function isAdmin(){return authUser?.role==="administrador";}
function userDisplayName(u){return u?`${u.firstName} ${u.lastName}`.trim():"Usuario";}
function setAuthError(ref,msg){if(ref)ref.textContent=msg;}
function clearAuthErrors(){setAuthError(authRefs.loginError,"");setAuthError(authRefs.registerError,"");}
function updateRoleUI(){const admin=isAdmin();if(authRefs.accountButtonLabel)authRefs.accountButtonLabel.textContent=isAuthenticated()?"Mi cuenta":"Iniciar sesión";if(authRefs.adminAccess){authRefs.adminAccess.hidden=!admin;authRefs.adminAccess.setAttribute("aria-hidden",String(!admin));}document.querySelectorAll("[data-admin-only]").forEach(el=>{el.hidden=!admin;el.setAttribute("aria-hidden",String(!admin));});if(authRefs.accountAdminButton)authRefs.accountAdminButton.hidden=!admin;}
async function renderAccountOrders(){if(!authUser||!authRefs.accountOrders)return;authRefs.accountOrders.innerHTML='<p class="account-orders-empty">Cargando tus compras…</p>';try{const r=await apiRequest("./api/orders/my-orders.php");const orders=r.orders||[];if(!orders.length){authRefs.accountOrders.innerHTML='<div class="account-orders-empty"><p class="eyebrow">Mis compras</p><p>Todavía no tienes compras registradas con esta cuenta.</p></div>';return;}authRefs.accountOrders.innerHTML=`<div class="account-orders-heading"><p class="eyebrow">Mis compras</p><span>${orders.length} ${orders.length===1?"pedido":"pedidos"}</span></div><div class="account-order-list">${orders.map(o=>`<article class="account-order-card"><div class="account-order-topline"><b>${safeText(o.id)}</b><span class="status-chip">${safeText(orderStatusLabel(o.status))}</span></div><p class="account-order-date">${new Date(o.createdAt).toLocaleString("es-ES",{dateStyle:"short",timeStyle:"short"})}</p><div class="account-order-products">${(o.items||[]).map(i=>`<span>${i.quantity}× ${safeText(i.title)}</span>`).join("")}</div><div class="account-order-total"><span>Total</span><b>${formatPrice(o.totals.total)}</b></div></article>`).join("")}</div>`;}catch(e){authRefs.accountOrders.innerHTML=`<p class="form-error">${safeText(e.message||"No se pudieron cargar tus compras.")}</p>`;}}
function renderAuthView(view){authRefs.loginView.hidden=view!=="login";authRefs.registerView.hidden=view!=="register";authRefs.accountView.hidden=view!=="account";if(view==="login"){authRefs.eyebrow.textContent="Acceso a tu cuenta";authRefs.title.textContent="Iniciar sesión";authRefs.loginLead.textContent="Inicia sesión para acceder al carrito, comprar y consultar tus pedidos.";}if(view==="register"){authRefs.eyebrow.textContent="Nuevo usuario";authRefs.title.textContent="Crear cuenta";}if(view==="account"){authRefs.eyebrow.textContent="Cuenta activa";authRefs.title.textContent="Mi cuenta";authRefs.accountName.textContent=userDisplayName(authUser);authRefs.accountEmail.textContent=authUser.email;authRefs.accountRole.textContent=isAdmin()?"Administrador":"Usuario";renderAccountOrders();}updateRoleUI();clearAuthErrors();}
function openAuth(view=isAuthenticated()?"account":"login",message=""){renderAuthView(view);if(authRefs.gateMessage){authRefs.gateMessage.textContent=message;authRefs.gateMessage.hidden=!message;}if(!authRefs.dialog.open)authRefs.dialog.showModal();}
function promptAuth(message){openAuth("login",message);}
function resetAuthForms(){if(authRefs.loginForm)authRefs.loginForm.reset();if(authRefs.registerForm)authRefs.registerForm.reset();}
function closeAuth(){if(authRefs.dialog.open)authRefs.dialog.close(); resetAuthForms();clearAuthErrors();if(authRefs.gateMessage){authRefs.gateMessage.textContent="";authRefs.gateMessage.hidden=true;}}
function requireAuth(message="Para continuar necesitas registrarte o iniciar sesión."){if(isAuthenticated())return true;promptAuth(message);return false;}
function showRegister(){renderAuthView("register");authRefs.registerForm.reset();authRefs.registerForm.querySelector("[name=firstName]").focus();}
function showLogin(){renderAuthView("login");authRefs.loginForm.reset();authRefs.loginForm.querySelector("[name=email]").focus();}
function syncCartAfterAuthChange(){if(typeof syncCartForCurrentUser==="function")syncCartForCurrentUser();if(typeof renderCart==="function")renderCart();}
async function loadSession(){try{const r=await apiRequest("./api/auth/session.php");csrfToken=r.csrfToken||csrfToken;authUser=r.user||null;updateRoleUI();}catch(e){authUser=null;updateRoleUI();console.warn("Sesión no disponible",e);}}
const authReady=loadSession();
if(authRefs.dialog)authRefs.dialog.addEventListener("close", resetAuthForms);
async function loginUser(form){const data=Object.fromEntries(new FormData(form).entries());const email=String(data.email||"").trim();const password=String(data.password||"");if(!/^\S+@\S+\.com$/i.test(email)||!password){setAuthError(authRefs.loginError,"Introduce un correo .com válido y tu contraseña.");return;}try{const r=await apiRequest("./api/auth/login.php",{method:"POST",body:JSON.stringify({email,password})});authUser=r.user;csrfToken=r.csrfToken;resetAuthForms();syncCartAfterAuthChange();renderAuthView("account");showToast(`Bienvenido/a, ${authUser.firstName}.`);}catch(e){setAuthError(authRefs.loginError,e.message);}}
async function createUser(form){const d=Object.fromEntries(new FormData(form).entries());const data={firstName:String(d.firstName||"").trim(),lastName:String(d.lastName||"").trim(),email:String(d.email||"").trim().toLowerCase(),password:String(d.password||"")};if(!/^[A-ZÁÉÍÓÚÜÑ][A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]*$/u.test(data.firstName)||!/^[A-ZÁÉÍÓÚÜÑ][A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]*$/u.test(data.lastName)){setAuthError(authRefs.registerError,"El nombre y los apellidos deben empezar por mayúscula.");return;}if(!/^[^\s@]+@[^\s@]+\.com$/i.test(data.email)){setAuthError(authRefs.registerError,"El correo debe contener @ y terminar en .com.");return;}if(!/^[A-ZÁÉÍÓÚÜÑ](?=.*\d).{5,}$/u.test(data.password)){setAuthError(authRefs.registerError,"La contraseña debe empezar por mayúscula, tener al menos 6 caracteres y contener un número.");return;}try{const r=await apiRequest("./api/auth/register.php",{method:"POST",body:JSON.stringify(data)});authUser=r.user;csrfToken=r.csrfToken;resetAuthForms();syncCartAfterAuthChange();renderAuthView("account");showToast("Cuenta creada correctamente.");}catch(e){setAuthError(authRefs.registerError,e.message);}}
async function logoutUser(){try{await apiRequest("./api/auth/logout.php",{method:"POST",body:"{}"});}catch(e){console.warn(e);}authUser=null;resetAuthForms();syncCartAfterAuthChange();updateRoleUI();closeAuth();closeCart();showToast("Has cerrado la sesión.");}
authRefs.loginForm?.addEventListener("submit",e=>{e.preventDefault();loginUser(e.currentTarget);});authRefs.registerForm?.addEventListener("submit",e=>{e.preventDefault();createUser(e.currentTarget);});authRefs.dialog?.addEventListener("click",e=>{if(e.target===authRefs.dialog)closeAuth();});
